version: '2'

services:
  bus-service:
    build: ./bus
    volumes: 
      - ./bus:/usr/src/app
    ports:
      - 5001:80
  train-service:
    build: ./train
    volumes:
      - ./train:/usr/src/app
    ports:
      - 5002:80

  incidents-service:
    build: ./incidents
    volumes:
      - ./incidents:/usr/src/app
    ports:
      - 5003:80

  website:
    image: php:7.1.20-apache-jessie
    volumes:
      - ./website:/var/www/html
    ports:
      - 80:80
    depends_on:
      - bus-service
      - train-service
      - incidents-service
